# permissions for end users to view containers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-viewer-role
rules:
- apiGroups:
  - workloads.operator.io
  resources:
  - containers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.operator.io
  resources:
  - containers/status
  verbs:
  - get
