# permissions for end users to edit containers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: container-editor-role
rules:
- apiGroups:
  - workloads.operator.io
  resources:
  - containers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.operator.io
  resources:
  - containers/status
  verbs:
  - get
